### ISSUE TITLE
部署后没有openAI内容返回

### ISSUE THREAD

**Issue by torans** [yangjian102621/chatgpt-plus#1]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

按照安装教程部署在海外节点（韩国）后，页面能正常显示，能获取到角色及收到"本项目已开放全部源代码：https://github.com/yangjian102621/chatgpt-plus..."等信息，但是发送消息却无法收到返回信息。
1，排查了Key没问题；
2，对比了Toml配置文件没看出异常。

### 重现步骤 🕹

运行日志：
2023-05-12T05:09:05.440Z        INFO    src/main.go:20  Loading config file: config.toml
2023-05-12T05:09:05.442Z        INFO    server/server.go:152    http://0.0.0.0:5678
2023-05-12T05:09:14.748Z        INFO    server/handler_chat.go:40       New websocket connected, IP: 127.0.0.1:39862, Username: Jran
2023-05-12T05:09:19.170Z        INFO    server/handler_chat.go:67       Receive a message: 1111
2023-05-12T05:09:19.170Z        INFO    server/handler_chat.go:132      会话上下文：[]
2023-05-12T05:09:19.170Z        INFO    server/handler_chat.go:179      Use API KEY: sk-Kxxx, PROXY: 
2023-05-12T05:09:19.369Z        ERROR   server/handler_chat.go:213      EOF
chatplus/server.(*Server).sendMessage
        /Users/ran/Developer/codes/chatgpt-plus/src/server/handler_chat.go:213
chatplus/server.(*Server).ChatHandle.func2
        /Users/ran/Developer/codes/chatgpt-plus/src/server/handler_chat.go:73
2023-05-12T05:09:19.369Z        INFO    server/handler_chat.go:78       回答完毕: 1111

### 你的应用配置信息

```toml
Title = "Chat-Plus AI 助手"
ConsoleTitle = "Chat-Plus 控制台"
Listen = "0.0.0.0:5678"
ProxyURL = [""]
AccessKey = "test"

[Session]
  SecretKey = "test001"
  Name = "CHAT_SESSION_ID"
  Path = "/"
  Domain = "chat.xxx.com"
  MaxAge = 86400
  Secure = false
  HttpOnly = false
  SameSite = 2

[ImgURL]
  WechatCard = ""
  WechatGroup = ""

[Manager]
  Username = "admin"
  Password = "admin123"

[Chat]
  ApiURL = "https://api.openai.com/v1/chat/completions"
  Model = "gpt-3.5-turbo"
  Temperature = 1.0
  MaxTokens = 1024
  EnableContext = true
  ChatContextExpireTime = 3600

  [[Chat.ApiKeys]]
    Value = "sk-xxxxxxx"
    LastUsed = 1683867437
```
