### ISSUE TITLE
按照流程安装

### ISSUE THREAD

**Issue by Morben** [yangjian102621/chatgpt-plus#4]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

找不到 xx.xx.x.x的网页找不到与以下网址对应的网页：http://x.x.x.x:5678/chat/
HTTP ERROR 404

我的8888端口被占用了，前端的端口我改成了8889

### 重现步骤 🕹

几乎是按照文档默认的配置安装的

### 你的应用配置信息

```toml
Title = "Chat-Plus AI 助手"
ConsoleTitle = "Chat-Plus 控制台"
Listen = "0.0.0.0:5678"
ProxyURL = [""]
AccessKey = ""

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80"
  Name = "CHAT_SESSION_ID"
  Path = "/"
  Domain = ""
  MaxAge = 86400
  Secure = false
  HttpOnly = false
  SameSite = 2

[ImgURL]
  WechatCard = "https://img.r9it.com/chatgpt/WX20230505-162403.png"
  WechatGroup = " https://img.r9it.com/chatgpt/WX20230505-162538.png"

[Manager]
  Username = "admin"
  Password = "admin123"

[Chat]
  ApiURL = "https://api.openai.com/v1/chat/completions"
  Model = "gpt-3.5-turbo"
  Temperature = 1.0
  MaxTokens = 1024
  EnableContext = true
  ChatContextExpireTime = 3600

  [[Chat.ApiKeys]]
    Value = "sk-xx"
    LastUsed = 0


服务正常启动
2023-05-20T04:42:19.134+0800	INFO	src/main.go:18	Loading config file: config.toml
2023-05-20T04:42:19.135+0800	INFO	server/server.go:136	Loading config file:aa dist
2023-05-20T04:42:19.135+0800	INFO	server/server.go:153	http://0.0.0.0:5678
```
