### ISSUE TITLE
配置好 mj后绘画完成历史记录里的图片无法正常显示，可能是oss的配置问题请指点一下谢谢

### ISSUE THREAD

**Issue by lp380490944** [yangjian102621/chatgpt-plus#42]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

MacOS

### Bug 描述 📝

配置好 mj后绘画完成历史记录里的图片无法正常显示

### 你的应用配置信息

```toml
Listen = "0.0.0.0:5678"
ProxyURL = "" # 如 http://127.0.0.1:7777
MysqlDns = "root:12345678@tcp(10.0.0.227:3307)/chatgpt_plus?charset=utf8&parseTime=True&loc=Local"
StaticDir = "./static" # 静态资源的目录
StaticUrl = "/static" # 静态资源访问 URL
AesEncryptKey = ""
WeChatBot = false

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80" # 注意：这个是 JWT Token 授权密钥，生产环境请务必更换
  MaxAge = 86400

[Manager]
  Username = "admin"
  Password = "admin123" # 如果是生产环境的话，这里管理员的密码记得修改

[Redis] # redis 配置信息
  Host = "10.0.0.227"
  Port = 6379
  Password = ""
  DB = 0

[ApiConfig] # 微博热搜，今日头条等函数服务 API 配置，此为第三方插件服务，如需使用请联系作者开通
  ApiURL = ""
  AppId = ""
  Token = ""

[SmsConfig] # 阿里云短信服务配置
  AccessKey = ""
  AccessSecret = ""
  Product = "Dysmsapi"
  Domain = "dysmsapi.aliyuncs.com"
  Sign = ""
  CodeTempId = ""

[ExtConfig] # MidJourney和微信机器人服务 API 配置，开通此功能需要配合 chatpgt-plus-exts 项目部署
  ApiURL = "" # 插件扩展 API 地址
  Token = "" # 这个 token 随便填，只要确保跟 chatgpt-plus-exts 项目的 token 一样就行

[OSS] # OSS 配置，用于存储 MJ 绘画图片
   Active = "minio" # 默认使用本地文件存储引擎
   [OSS.Local]
     BasePath = "./static/upload" # 本地文件上传根路径
     BaseURL = "http://10.0.0.227:5678/static/upload" # 本地上传文件根 URL 如果是线上，则直接设置为 /static/upload 即可
   [OSS.Minio]
     Endpoint = "http://mydomain:9000" # 如 172.22.11.200:9000
     AccessKey = "YG8xX0bjttgnqktgBY" # 自己去 Minio 控制台去创建一个 Access Key
     AccessSecret = "1twhZ0kd9IFl91N5eJUTyMNyGMEO0VasG"
     Bucket = "chatgpt-plus" # 替换为你自己创建的 Bucket，注意要给 Bucket 设置公开的读权限，否则会出现图片无法显示。
     UseSSL = false
     Domain = "http://mydomain:9000" # 地址必须是能够通过公网访问的，否则会出现图片无法显示。
   [OSS.QiNiu] # 七牛云 OSS 配置
       Zone = "z2" # 区域，z0：华东，z1: 华北，na0：北美，as0：新加坡
       AccessKey = ""
       AccessSecret = ""
       Bucket = ""
       Domain = "" # OSS Bucket 所绑定的域名，如 https://img.r9it.com

[MjConfig]
  Enabled = true
  UserToken = "MTE1NDYyNzM0ODAzODE3NjgwOA.GICqlF.N2zX1i621Qsz"#已经删除部分
  BotToken = "MTE1NTY5ODgwNzE4MSwnuruBK-5AsZqXjhPet0xRE"#已经删除部分
  GuildId = "1155691"#已经删除部分
  ChanelId = "115569"#已经删除部分

[SdConfig]
  Enabled = false
  ApiURL = "http://172.22.11.200:7860"
  ApiKey = ""
  Txt2ImgJsonPath = "res/text2img.json"
```
