### ISSUE TITLE
3.1.7

### ISSUE THREAD

**Issue by asipirin1120** [yangjian102621/chatgpt-plus#50]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

环境：
Vultr大阪，debian-11.7，内核5.10.0-25-amd64，MySQL 8.2.0，Redis 6.2.14

部署版本：3.1.7

按部署文档逐步部署完成后，chat-gpt-plus-api日志一直提示如下错误，并重复重启：
Table 'gpt-plus.chatgpt_configs' doesn't exist

### 重现步骤 🕹

按照文档逐步部署，并启动docker拉取镜像后发生。

### 你的应用配置信息

```toml
Listen = "0.0.0.0:5678"
ProxyURL = "" # 如 http://127.0.0.1:7777
MysqlDns = "root:------------@tcp(mysql:3306)/gpt-plus?charset=utf8&parseTime=True&loc=Local"
StaticDir = "./static" # 静态资源的目录
StaticUrl = "/static" # 静态资源访问 URL
AesEncryptKey = ""
WeChatBot = false

[Session]
  SecretKey = "------------------------------------g80" # 注意：这个是 JWT Token 授权密钥，生产环境请务必更换
  MaxAge = 86400

[Manager]
  Username = "admin"
  Password = "admin123" # 如果是生产环境的话，这里管理员的密码记得修改

[Redis] # redis 配置信息
  Host = "redis"
  Port = 6379
  Password = "------------------GP7"
  DB = 0

```
