### ISSUE TITLE
前后端分离部署错误，网络请求错误。

### ISSUE THREAD

**Issue by nuass** [yangjian102621/chatgpt-plus#8]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-4

### 操作系统

Linux
云服务器
192.168.0.129为司有IP

### Bug 描述 📝

前后端分类部署，
后端、前端服务都启动

### 重现步骤 🕹

可重现11111111111

### 你的应用配置信息

```toml
Title = "Chat-Plus AI 助手"
ConsoleTitle = "Chat-Plus 控制台"
Listen = "192.168.0.129:5678"
ProxyURL = ["YOUR_PROXY_URL"]
AccessKey = "YOUR_ACCESS_KEY"

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80"
  Name = "CHAT_SESSION_ID"
  Path = "/"
  Domain = "192.168.0.129"
  MaxAge = 86400
  Secure = false
  HttpOnly = false
  SameSite = 2

[ImgURL]
  WechatCard = "https://img.r9it.com/chatgpt/WX20230505-162403.png"
  WechatGroup = " https://img.r9it.com/chatgpt/WX20230505-162538.png"

[Manager]
  Username = "admin"
  Password = "admin123"

[Chat]
  ApiURL = "https://api.openai.com/v1/chat/completions"
  Model = "gpt-3.5-turbo"
  Temperature = 1.0
  MaxTokens = 1024
  EnableContext = true
  ChatContextExpireTime = 3600

  [[Chat.ApiKeys]]
    Value = "1233333333333333333333333333333333333333333333333333"
    LastUsed = 0

```
VUE_APP_API_HOST=http://192.168.0.129:5678
VUE_APP_WS_HOST=ws://192.168.0.129:5678
