### ISSUE TITLE
输入口令后无法进入

### ISSUE THREAD

**Issue by awewu** [yangjian102621/chatgpt-plus#9]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

![image](https://github.com/yangjian102621/chatgpt-plus/assets/57051851/5e28fbac-ebd2-45da-9b7e-34aaa7c39a01)
后台可以登录，前台输入口令后一直转圈圈

### 重现步骤 🕹

code包，运行后就这样

### 你的应用配置信息

```toml
Title = "Chat-Plus AI 助手"
ConsoleTitle = "Chat-Plus 控制台"
Listen = "192.168.11.138:5678"
ProxyURL = ["127.0.0.1:7890"]
AccessKey = "YOUR_ACCESS_KEY"

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80"
  Name = "CHAT_SESSION_ID"
  Path = "/"
  Domain = "192.168.11.138"
  MaxAge = 86400
  Secure = false
  HttpOnly = false
  SameSite = 2

[ImgURL]
  WechatCard = "https://img.r9it.com/chatgpt/WX20230505-162403.png"
  WechatGroup = " https://img.r9it.com/chatgpt/WX20230505-162538.png"

[Manager]
  Username = "admin"
  Password = "admin123"

[Chat]
  ApiURL = "https://api.openai.com/v1/chat/completions"
  Model = "gpt-3.5-turbo"
  Temperature = 1.0
  MaxTokens = 1024
  EnableContext = true
  ChatContextExpireTime = 3600

```
